<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Reviews:Admin:Review@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new review'); ?></a></li>
		 <li><a href="<?php echo $this->url('Reviews:Admin:Config@indexAction'); ?>"><i class="glyphicon glyphicon-tasks"></i> <?php $this->show('Configuration'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($reviews)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Reviews:Admin:Review@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Reviews:Admin:Review@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes');?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
		 
	  </ul>
	</div>
</div>

<?php $this->loadPartial('items-per-page', array('caption' => 'Reviews')); ?>

<form>
    <div class="table-responsive">
        <?= Grid::render($reviews, array(
            'batch' => true,
            'pk' => 'id',
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name'
                ),

                array(
                    'column' => 'email'
                ),

                array(
                    'column' => 'timestamp',
                    'label' => 'Date',
                    'value' => function($review) use ($dateFormat){
                        return date($dateFormat, $review->getTimestamp());
                    }
                ),

                array(
                    'column' => 'ip',
                    'label' => 'IP-Address'
                ),

                array(
                    'column' => 'published',
                    'value' => function($review){
                        return Element::checkbox(sprintf('published[%s]', $review->getId()), $review->getPublished());
                    }
                )
            ),

            'actions' => array(
                'edit' => function($review){
                    return Icon::edit(
                        $this->url('Reviews:Admin:Review@editAction', $review->getId()),
                        $this->translate('Edit this review')
                    );
                },

                'remove' => function($review){
                    return Icon::remove(
                        $this->url('Reviews:Admin:Review@deleteAction', $review->getId()),
                        $this->translate('Remove this review')
                    );
                }
            )

        ), $this->translator); ?>        
        
		<?php if (empty($reviews)): ?>
		<div class="center-block">
			<h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No reviews'); ?></h2>
		</div>
		<?php endif; ?>
	</div>
</form>

<?php $this->loadPartial('paginator'); ?>
