<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', [
        'items' => [
            'Reviews:Admin:Review@addAction' => 'Add new review',
            'Reviews:Admin:Config@indexAction' => 'Configuration',
        ],

        'actions' => [
            'data' => $reviews,
            'save' => 'Reviews:Admin:Review@tweakAction',
            'delete' => 'Reviews:Admin:Review@deleteAction'
        ]
    ]); ?>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', ['caption' => 'Reviews']); ?>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($reviews, [
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#'
                    ],

                    [
                        'column' => 'name'
                    ],

                    [
                        'column' => 'email'
                    ],

                    [
                        'column' => 'timestamp',
                        'label' => 'Date',
                        'value' => function($review) use ($dateFormat){
                            return date($dateFormat, $review->getTimestamp());
                        }
                    ],

                    [
                        'column' => 'ip',
                        'label' => 'IP-Address'
                    ],

                    [
                        'column' => 'published',
                        'value' => function($review){
                            return Element::checkbox(sprintf('published[%s]', $review->getId()), $review->getPublished());
                        }
                    ]
                ],

                'actions' => [
                    function($review){
                        return Icon::edit(
                            $this->url('Reviews:Admin:Review@editAction', $review->getId()),
                            $this->translate('Edit this review')
                        );
                    },

                    function($review){
                        return Icon::remove(
                            $this->url('Reviews:Admin:Review@deleteAction', $review->getId()),
                            $this->translate('Remove this review')
                        );
                    }
                ]
            ])); ?>        
            
            <?php if (empty($reviews)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No reviews'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>

</div>