<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', array(
        'items' => array(
            'Reviews:Admin:Review@addAction' => 'Add new review',
            'Reviews:Admin:Config@indexAction' => 'Configuration',
        ),

        'actions' => array(
            'data' => $reviews,
            'save' => 'Reviews:Admin:Review@tweakAction',
            'delete' => 'Reviews:Admin:Review@deleteAction'
        )
    )); ?>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Reviews')); ?>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($reviews, array(
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'name'
                    ),

                    array(
                        'column' => 'email'
                    ),

                    array(
                        'column' => 'timestamp',
                        'label' => 'Date',
                        'value' => function($review) use ($dateFormat){
                            return date($dateFormat, $review->getTimestamp());
                        }
                    ),

                    array(
                        'column' => 'ip',
                        'label' => 'IP-Address'
                    ),

                    array(
                        'column' => 'published',
                        'value' => function($review){
                            return Element::checkbox(sprintf('published[%s]', $review->getId()), $review->getPublished());
                        }
                    )
                ),

                'actions' => array(
                    'edit' => function($review){
                        return Icon::edit(
                            $this->url('Reviews:Admin:Review@editAction', $review->getId()),
                            $this->translate('Edit this review')
                        );
                    },

                    'remove' => function($review){
                        return Icon::remove(
                            $this->url('Reviews:Admin:Review@deleteAction', $review->getId()),
                            $this->translate('Remove this review')
                        );
                    }
                )
            ))); ?>        
            
            <?php if (empty($reviews)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No reviews'); ?></h2>
            </div>
            <?php endif; ?>
        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>

</div>
